-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Imageboard.Object exposing (..)


type CreateImagePayload
    = CreateImagePayload


type DeleteImagePayload
    = DeleteImagePayload


type Image
    = Image


type ImagesConnection
    = ImagesConnection


type ImagesEdge
    = ImagesEdge


type PageInfo
    = PageInfo


type UpdateImagePayload
    = UpdateImagePayload
