-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Imageboard.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Imageboard.Scalar exposing (defaultCodecs)


type alias Cursor
    = Imageboard.Scalar.Cursor


type alias Id
    = Imageboard.Scalar.Id


codecs : Imageboard.Scalar.Codecs Cursor Id
codecs =
    Imageboard.Scalar.defineCodecs
        {
        codecCursor = defaultCodecs.codecCursor    , codecId = defaultCodecs.codecId
        }
