-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Imageboard.Object.ImagesConnection exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Imageboard.Object
import Imageboard.Interface
import Imageboard.Union
import Imageboard.Scalar
import Imageboard.InputObject
import Imageboard.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| A list of `Image` objects.
-}
nodes : SelectionSet decodesTo Imageboard.Object.Image
 -> SelectionSet (List (Maybe decodesTo)) Imageboard.Object.ImagesConnection
nodes object____ =
      Object.selectionForCompositeField "nodes" [] (object____) (Basics.identity >> Decode.nullable >> Decode.list)


{-| A list of edges which contains the `Image` and cursor to aid in pagination.
-}
edges : SelectionSet decodesTo Imageboard.Object.ImagesEdge
 -> SelectionSet (List decodesTo) Imageboard.Object.ImagesConnection
edges object____ =
      Object.selectionForCompositeField "edges" [] (object____) (Basics.identity >> Decode.list)


{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo Imageboard.Object.PageInfo
 -> SelectionSet decodesTo Imageboard.Object.ImagesConnection
pageInfo object____ =
      Object.selectionForCompositeField "pageInfo" [] (object____) (Basics.identity)


{-| The count of *all* `Image` you could get from the connection.
-}
totalCount : SelectionSet Int Imageboard.Object.ImagesConnection
totalCount =
      Object.selectionForField "Int" "totalCount" [] (Decode.int)
