-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Imageboard.Object.Image exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Imageboard.Object
import Imageboard.Interface
import Imageboard.Union
import Imageboard.Scalar
import Imageboard.InputObject
import Imageboard.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| A globally unique identifier. Can be used in various places throughout the system to identify this single value.
-}
nodeId : SelectionSet Imageboard.ScalarCodecs.Id Imageboard.Object.Image
nodeId =
      Object.selectionForField "ScalarCodecs.Id" "nodeId" [] (Imageboard.ScalarCodecs.codecs |> Imageboard.Scalar.unwrapCodecs |> .codecId |> .decoder)


id : SelectionSet Int Imageboard.Object.Image
id =
      Object.selectionForField "Int" "id" [] (Decode.int)


title : SelectionSet String Imageboard.Object.Image
title =
      Object.selectionForField "String" "title" [] (Decode.string)


url : SelectionSet String Imageboard.Object.Image
url =
      Object.selectionForField "String" "url" [] (Decode.string)
