-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Imageboard.Object.PageInfo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Imageboard.Object
import Imageboard.Interface
import Imageboard.Union
import Imageboard.Scalar
import Imageboard.InputObject
import Imageboard.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| When paginating forwards, are there more items?
-}
hasNextPage : SelectionSet Bool Imageboard.Object.PageInfo
hasNextPage =
      Object.selectionForField "Bool" "hasNextPage" [] (Decode.bool)


{-| When paginating backwards, are there more items?
-}
hasPreviousPage : SelectionSet Bool Imageboard.Object.PageInfo
hasPreviousPage =
      Object.selectionForField "Bool" "hasPreviousPage" [] (Decode.bool)


{-| When paginating backwards, the cursor to continue.
-}
startCursor : SelectionSet (Maybe Imageboard.ScalarCodecs.Cursor) Imageboard.Object.PageInfo
startCursor =
      Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "startCursor" [] (Imageboard.ScalarCodecs.codecs |> Imageboard.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)


{-| When paginating forwards, the cursor to continue.
-}
endCursor : SelectionSet (Maybe Imageboard.ScalarCodecs.Cursor) Imageboard.Object.PageInfo
endCursor =
      Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "endCursor" [] (Imageboard.ScalarCodecs.codecs |> Imageboard.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)
