@startuml sequence-diagram-remove-image

actor Editor

Editor->PostGraphile: Make a GraphQL mutation
PostGraphile->PostgreSQL: Make a SQL query
PostgreSQL-->PostGraphile
PostGraphile-->Editor

@enduml